# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # attribute specifies that, for the operating system, the workflow runs on ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # get code from repo into VM
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
     # setup right version of Node.js
     # setup right version of Node.js with ${{ matrix.node-version }} attribute
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # npm ci command installs dependencies from the package-lock.json file
    # npm run build --if-present runs a build script if it exists
    # npm test runs the testing framework
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
